services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: example_root_password
      MYSQL_DATABASE: example_db
      MYSQL_USER: example_user
      MYSQL_PASSWORD: example_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mysql_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5

  phpmyadmin:
    image: phpmyadmin:latest
    platform: linux/arm64/v8
    container_name: phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: example_user
      PMA_PASSWORD: example_password
    networks:
      - mysql_network
    depends_on:
      db:
        condition: service_healthy

  fastapi:
    build: .
    container_name: fastapi_app
    volumes:
      - .:/app
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=example_user
      - DB_PASSWORD=example_password
      - DB_NAME=example_db
    ports:
      - "8000:80"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - mysql_network

  frontend:
    build: ../front-end_hlib
    ports:
      - "4200:80"
    networks:
      - mysql_network

volumes:
  db_data:

networks:
  mysql_network:
